# Only fake ACL lifecycle/ABI evidence. No actual OM kernels or NPU timing.
cmake_policy(SET CMP0054 NEW)
set(ENV{QWEN35_DFLASH_FAKE_STATIC_SPLIT} 1)
set(model_args
  --target-prefill "${PREFILL}" --target-prefill-sha256 "${PREFILL_SHA}"
  --target-decode1 "${DECODE}" --target-decode1-sha256 "${DECODE_SHA}"
  --draft-propose "${DRAFT}" --draft-propose-sha256 "${DRAFT_SHA}"
  --target-verify-commit "${VERIFY}" --target-verify-commit-sha256 "${VERIFY_SHA}")
string(REPEAT "1," 16 prefix)
set(prompt "${prefix}10")
function(run_case name)
  set(output "${OUTPUT}-${name}.json")
  file(REMOVE "${output}" "${output}.tmp")
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
    --prompt-token-ids "${prompt}" --max-draft-tokens 3 ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "static split ${name}: ${stderr}")
  endif()
  file(READ "${output}" report)
  string(JSON topology GET "${report}" abi physical_topology)
  string(JSON models LENGTH "${report}" models)
  string(JSON head GET "${report}" execution_io_counters target_prefill_head_executions)
  string(JSON fused GET "${report}" execution_io_counters fused_speculative_step_executions)
  string(JSON mismatch GET "${report}" ordinary_parity token_id_mismatches)
  string(JSON draft GET "${report}" execution_io_counters draft_propose_executions)
  string(JSON physical GET "${report}" execution_io_counters draft_static_physical_feature_rows)
  string(JSON source GET "${report}" execution_io_counters draft_static_source_feature_rows)
  string(JSON padding GET "${report}" execution_io_counters draft_static_padding_rows)
  math(EXPR expected "${draft} * 64")
  math(EXPR total "${source} + ${padding}")
  if(NOT models EQUAL 4 OR NOT head EQUAL 0 OR NOT fused EQUAL 0 OR
     NOT mismatch EQUAL 0 OR NOT physical EQUAL expected OR NOT total EQUAL expected OR
     NOT topology STREQUAL "merged-prefill-four-static-split-v1")
    message(FATAL_ERROR "static split ABI/parity/accounting differs: ${report}")
  endif()
  foreach(scope model_memory_query execution_io_counters)
    foreach(field draft_dynamic_shape draft_dynamic_gear_count draft_om_dynamic_gear_count
                  draft_prefill_dynamic_gear_count draft_verify_dynamic_gear_count)
      string(JSON count GET "${report}" ${scope} ${field})
      if(count)
        message(FATAL_ERROR "static split used dynamic API: ${report}")
      endif()
    endforeach()
  endforeach()
  string(JSON policy GET "${report}" model_residency policy)
  if(policy STREQUAL "phase-resident")
    string(JSON groups GET "${report}" model_residency split_group_loads)
    string(JSON first_drafts GET "${report}" execution_io_counters prefill_draft_propose_executions)
    string(JSON peak GET "${report}" model_residency peak_resident_models)
    string(JSON current GET "${report}" model_residency current_resident_models)
    string(JSON switches GET "${report}" model_residency model_switches)
    string(JSON loads GET "${report}" model_residency model_loads)
    string(JSON unloads GET "${report}" model_residency model_unloads)
    string(JSON excluded GET "${report}" protocol model_load_excluded_from_latency)
    math(EXPR expected_loads "4 + ${switches} + ${groups}")
    math(EXPR expected_unloads "${loads} - ${current}")
    if(NOT groups EQUAL first_drafts OR peak GREATER 2 OR
       NOT loads EQUAL expected_loads OR NOT unloads EQUAL expected_unloads OR excluded)
      message(FATAL_ERROR "static split group residency differs: ${report}")
    endif()
  endif()
endfunction()

foreach(policy phase-resident all-resident)
  foreach(reset async-memset immutable-zero)
    foreach(feature fixed-16 committed-prefix)
      foreach(window 1 2 8)
        run_case("${policy}-${reset}-${feature}-${window}"
          --model-residency-policy "${policy}" --state-reset-policy "${reset}"
          --draft-feature-policy "${feature}" --dflash-sync-window "${window}")
      endforeach()
    endforeach()
  endforeach()
endforeach()
foreach(tokens 1 2)
  run_case("short-${tokens}" --max-new-tokens "${tokens}")
endforeach()
foreach(eos 11 15 40)
  run_case("eos-${eos}" --eos-token-ids "${eos}"
    --prefill-completion-policy coalesce-first-verify --dflash-sync-window 8)
endforeach()
set(ENV{QWEN35_DFLASH_FAKE_ZERO_ACCEPT} 1)
run_case("zero-accept" --zero-accept-fallback-policy request-target-only --dflash-sync-window 8)
unset(ENV{QWEN35_DFLASH_FAKE_ZERO_ACCEPT})

# Same artifacts: the grouped budget holds Draft+Verify, not only max(single).
set(ENV{QWEN35_DFLASH_FAKE_WEIGHT_SCALE} 4096)
set(ENV{QWEN35_DFLASH_FAKE_DEVICE_LIMIT} 3145728)
run_case("budget-phase")
file(READ "${OUTPUT}-budget-phase.json" budget)
string(JSON allocated GET "${budget}" model_memory_query allocated_weight_bytes)
if(NOT allocated EQUAL 2097152)
  message(FATAL_ERROR "Draft+Verify weight slices were not simultaneously budgeted")
endif()
set(output "${OUTPUT}-budget-all.json")
file(REMOVE "${output}" "${output}.tmp")
execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
  --prompt-token-ids "${prompt}" --model-residency-policy all-resident
  RESULT_VARIABLE result ERROR_VARIABLE stderr)
if(result EQUAL 0 OR EXISTS "${output}" OR NOT stderr MATCHES "aclrtMalloc owner=.*weights")
  message(FATAL_ERROR "all-resident budget did not fail closed: ${stderr}")
endif()
unset(ENV{QWEN35_DFLASH_FAKE_WEIGHT_SCALE})
unset(ENV{QWEN35_DFLASH_FAKE_DEVICE_LIMIT})

foreach(fault FAIL_RELOAD FAIL_VERIFY_GROUP_LOAD FAIL_UNLOAD RELOAD_ABI_DRIFT FAIL_EXECUTE)
  set(ENV{QWEN35_DFLASH_FAKE_${fault}} 1)
  set(output "${OUTPUT}-${fault}.json")
  file(REMOVE "${output}" "${output}.tmp")
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
    --prompt-token-ids "${prompt}" RESULT_VARIABLE result ERROR_VARIABLE stderr)
  if(result EQUAL 0 OR EXISTS "${output}" OR stderr MATCHES "fake ACL cleanup left live")
    message(FATAL_ERROR "static split fault ${fault} did not fail cleanly: ${stderr}")
  endif()
  unset(ENV{QWEN35_DFLASH_FAKE_${fault}})
endforeach()
