# Host-only diagnostic validation. No real model accuracy claim.
cmake_policy(SET CMP0054 NEW)
set(ENV{QWEN35_DFLASH_FAKE_STATIC_SPLIT} 1)
set(model_args
  --target-prefill "${PREFILL}" --target-prefill-sha256 "${PREFILL_SHA}"
  --target-decode1 "${DECODE}" --target-decode1-sha256 "${DECODE_SHA}"
  --draft-propose "${DRAFT}" --draft-propose-sha256 "${DRAFT_SHA}"
  --target-verify-commit "${VERIFY}" --target-verify-commit-sha256 "${VERIFY_SHA}")
# An explicit fake expectation proves the CLI path reaches aclInit, without
# pretending the fake runtime writes real operator dumps.
set(dump_config "${OUTPUT}-acl.json")
file(WRITE "${dump_config}" "{}")
set(ENV{QWEN35_DFLASH_FAKE_EXPECT_DUMP_CONFIG} "${dump_config}")
foreach(fault none correction bonus gdr cursor kv-tail kv-live nan fp16 padded-cursor)
  set(ENV{QWEN35_DFLASH_FAKE_DIAGNOSTIC_FAULT} "${fault}")
  set(output "${OUTPUT}-${fault}.json")
  file(REMOVE "${output}" "${output}.tmp" "${output}.failure.json" "${output}.failure.json.tmp")
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
    --prompt-token-ids 10 --max-new-tokens 32 --max-draft-tokens 3 --progress false
    --diagnose-target-parity true --diagnostic-max-transactions 2
    --acl-dump-config "${dump_config}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE stderr)
  if(NOT EXISTS "${output}")
    message(FATAL_ERROR "diagnostic report missing: ${fault}: ${stderr}")
  endif()
  file(READ "${output}" report)
  string(JSON kind GET "${report}" report_kind)
  string(JSON status GET "${report}" status)
  string(JSON formal GET "${report}" formal_latency_evidence)
  string(JSON count GET "${report}" diagnostic captured_transactions)
  string(JSON stop GET "${report}" diagnostic capture_stop_reason)
  string(JSON extra_device GET "${report}" diagnostic extra_device_state_bytes)
  string(JSON dump_path GET "${report}" acl_dump_config path)
  string(JSON trace_count LENGTH "${report}" model_execution_trace)
  string(JSON capture_start GET "${report}" diagnostic transactions 0 capture_execution_trace_range 0)
  string(JSON capture_end GET "${report}" diagnostic transactions 0 capture_execution_trace_range 1)
  if(NOT dump_path STREQUAL dump_config OR trace_count LESS 1 OR NOT capture_end GREATER capture_start)
    message(FATAL_ERROR "dump config or execution trace missing: ${report}")
  endif()
  string(JSON inputs GET "${report}" diagnostic transactions 0 replayed_input_ids)
  string(JSON cursor GET "${report}" diagnostic transactions 0 incoming_state_vs_chained_decode1 reference_cursor)
  if(NOT kind STREQUAL "cpp-ascendcl-target-parity-diagnostic" OR NOT status STREQUAL "DIAGNOSTIC"
     OR formal OR NOT count EQUAL 2 OR NOT extra_device EQUAL 0 OR NOT cursor EQUAL 1
     OR NOT stop STREQUAL "transaction-limit" OR stderr MATCHES "stage=benchmark")
    message(FATAL_ERROR "incorrect diagnostic scope: ${report}")
  endif()
  if(fault STREQUAL "correction" OR fault STREQUAL "bonus" OR fault STREQUAL "gdr" OR fault STREQUAL "cursor")
    if(NOT result EQUAL 1 OR NOT EXISTS "${output}.failure.json")
      message(FATAL_ERROR "diagnostic mismatch did not retain nonzero exit: ${stderr}")
    endif()
  elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "diagnostic failed: ${fault}: ${stderr}")
  endif()
  if(fault STREQUAL "correction")
    string(JSON role GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens mismatches 0 token_role)
    string(JSON row GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens mismatches 0 verify_row)
    string(JSON token_index GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens mismatches 0 generated_token_index)
    string(JSON expected GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens mismatches 0 expected_token)
    string(JSON actual GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens mismatches 0 actual_token)
    string(JSON absolute_index GET "${report}" diagnostic first_token_mismatch absolute_token_index)
    if(NOT role STREQUAL "target-correction" OR NOT row EQUAL 2 OR NOT token_index EQUAL 3
       OR NOT expected EQUAL 14 OR NOT actual EQUAL 114 OR NOT absolute_index EQUAL 4)
      message(FATAL_ERROR "wrong correction/row localization: ${report}")
    endif()
  elseif(fault STREQUAL "bonus")
    string(JSON role GET "${report}" diagnostic first_token_mismatch token_role)
    string(JSON expected GET "${report}" diagnostic first_token_mismatch expected_token)
    string(JSON actual GET "${report}" diagnostic first_token_mismatch actual_token)
    if(NOT role STREQUAL "target-bonus" OR NOT expected EQUAL 15 OR NOT actual EQUAL 115)
      message(FATAL_ERROR "all-accepted bonus mislabeled as correction: ${report}")
    endif()
  elseif(fault STREQUAL "gdr")
    string(JSON error GET "${report}" diagnostic transactions 1 incoming_state_vs_chained_decode1 tensors 1 layers 0 max_finite_abs_error)
    if(NOT error EQUAL 1)
      message(FATAL_ERROR "previous state drift was not localized: ${report}")
    endif()
  elseif(fault STREQUAL "kv-tail" OR fault STREQUAL "kv-live")
    string(JSON diffs GET "${report}" diagnostic transactions 0 same_input_state_decode1_state_vs_verify tensors 2 layers 0 bitwise_different_elements)
    if((fault STREQUAL "kv-tail" AND NOT diffs EQUAL 0) OR (fault STREQUAL "kv-live" AND NOT diffs EQUAL 1))
      message(FATAL_ERROR "paged KV live/tail comparison incorrect: ${report}")
    endif()
  elseif(fault STREQUAL "nan")
    string(JSON nonfinite GET "${report}" diagnostic transactions 0 same_input_state_decode1_state_vs_verify tensors 1 layers 0 actual_nonfinite)
    string(JSON value_type TYPE "${report}" diagnostic transactions 0 same_input_state_decode1_state_vs_verify tensors 1 layers 0 first_bitwise_difference actual)
    if(NOT nonfinite EQUAL 1 OR NOT value_type STREQUAL "NULL")
      message(FATAL_ERROR "nonfinite value not safely encoded: ${report}")
    endif()
  elseif(fault STREQUAL "fp16")
    string(JSON numeric GET "${report}" diagnostic transactions 0 same_input_state_decode1_state_vs_verify tensors 0 layers 0 numeric_different_elements)
    string(JSON bits GET "${report}" diagnostic transactions 0 same_input_state_decode1_state_vs_verify tensors 0 layers 0 bitwise_different_elements)
    if(NOT numeric EQUAL 0 OR NOT bits EQUAL 1)
      message(FATAL_ERROR "FP16 signed-zero diagnostic lost: ${report}")
    endif()
  endif()
  # Existing raw diagnostic is evidence, not an overwrite target.
  file(SHA256 "${output}" before)
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
    --prompt-token-ids 10 --diagnose-target-parity true
    RESULT_VARIABLE retry OUTPUT_QUIET ERROR_VARIABLE stderr)
  file(SHA256 "${output}" after)
  if(NOT retry EQUAL 1 OR NOT before STREQUAL after OR NOT stderr MATCHES "already exists")
    message(FATAL_ERROR "diagnostic overwrite admission failed")
  endif()
endforeach()
unset(ENV{QWEN35_DFLASH_FAKE_DIAGNOSTIC_FAULT})
unset(ENV{QWEN35_DFLASH_FAKE_EXPECT_DUMP_CONFIG})

# No transaction was executed: do not claim a token comparison PASS.
set(output "${OUTPUT}-eos.json")
file(REMOVE "${output}" "${output}.tmp" "${output}.failure.json")
execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
  --prompt-token-ids 10 --eos-token-ids 11 --diagnose-target-parity true
  RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE stderr)
file(READ "${output}" report)
string(JSON count GET "${report}" diagnostic captured_transactions)
string(JSON parity GET "${report}" diagnostic token_parity)
if(NOT result EQUAL 0 OR NOT count EQUAL 0 OR NOT parity STREQUAL "NOT_CHECKED")
  message(FATAL_ERROR "early EOS overclaimed diagnostic coverage: ${stderr} ${report}")
endif()

# Preserve the real scheduler's zero-accept fallback and short/EOS requests.
foreach(edge fallback accepted-eos terminal)
  unset(ENV{QWEN35_DFLASH_FAKE_ZERO_ACCEPT})
  if(edge STREQUAL "fallback")
    set(ENV{QWEN35_DFLASH_FAKE_ZERO_ACCEPT} 1)
    set(extra --max-new-tokens 32 --max-draft-tokens 3 --zero-accept-fallback-policy request-target-only)
  elseif(edge STREQUAL "accepted-eos")
    set(extra --max-new-tokens 32 --max-draft-tokens 3 --eos-token-ids 13)
  else()
    set(extra --max-new-tokens 2 --max-draft-tokens 15)
  endif()
  set(output "${OUTPUT}-${edge}.json")
  file(REMOVE "${output}" "${output}.tmp" "${output}.failure.json")
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${output}"
    --prompt-token-ids 10 --diagnose-target-parity true --diagnostic-max-transactions 2
    ${extra} RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE stderr)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "edge diagnostic failed: ${edge}: ${stderr}")
  endif()
  file(READ "${output}" report)
  string(JSON count GET "${report}" diagnostic captured_transactions)
  if(edge STREQUAL "fallback")
    string(JSON path GET "${report}" diagnostic transactions 1 path)
    string(JSON k GET "${report}" diagnostic transactions 1 proposal_limit)
    if(NOT count EQUAL 2 OR NOT path STREQUAL "target-only-verify" OR NOT k EQUAL 0)
      message(FATAL_ERROR "diagnostic changed zero-accept fallback scheduling: ${report}")
    endif()
  else()
    string(JSON stop GET "${report}" diagnostic capture_stop_reason)
    string(JSON compared GET "${report}" diagnostic transactions 0 same_input_state_decode1_tokens compared_rows)
    if(NOT count EQUAL 1 OR (edge STREQUAL "accepted-eos" AND (NOT stop STREQUAL "eos" OR NOT compared EQUAL 2))
       OR (edge STREQUAL "terminal" AND (NOT stop STREQUAL "length" OR NOT compared EQUAL 2)))
      message(FATAL_ERROR "diagnostic changed short/EOS scheduling: ${report}")
    endif()
  endif()
endforeach()
unset(ENV{QWEN35_DFLASH_FAKE_ZERO_ACCEPT})

# Unsupported timing/policy combinations must fail before any model load.
foreach(bad_case evidence window coalesce limit disabled dump-without-diagnostic)
  if(bad_case STREQUAL "evidence")
    set(extra --diagnose-target-parity true --measurement-protocol evidence)
  elseif(bad_case STREQUAL "window")
    set(extra --diagnose-target-parity true --dflash-sync-window 2)
  elseif(bad_case STREQUAL "coalesce")
    set(extra --diagnose-target-parity true --prefill-completion-policy coalesce-first-verify)
  elseif(bad_case STREQUAL "limit")
    set(extra --diagnose-target-parity true --diagnostic-max-transactions 5)
  elseif(bad_case STREQUAL "dump-without-diagnostic")
    set(extra --acl-dump-config "${dump_config}")
  else()
    set(extra --diagnostic-max-transactions 2)
  endif()
  execute_process(COMMAND "${RUNNER}" ${model_args} --output "${OUTPUT}-invalid-${bad_case}.json"
    --prompt-token-ids 10 ${extra} RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE stderr)
  if(NOT result EQUAL 1 OR stderr MATCHES "stage=load-")
    message(FATAL_ERROR "invalid diagnostic options reached model loading: ${stderr}")
  endif()
endforeach()
